function [freq, data_extr] = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [FREQ, DATA_EXTR] = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as column
%  vectors.
%
%  [FREQ, DATA_EXTR] = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  [freq, data_extr] = importfile("C:\Users\GETMANI\Documents\MATLAB\EELS_sim\EELS_simulations\Input_impedance_analysis\Z0_const_wire_real.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 06-Aug-2023 13:38:51

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["freq", "data_extr"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
freq = tbl.freq;
data_extr = tbl.data_extr;
end